services:
  viatab-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/mydatabase
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=secret
    depends_on:
      - postgres
    restart: always
    networks:
      - viatab-network

  frontend:
    build:
      context: C:/Users/tony8/WebstormProjects/via_tab
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - viatab-app
    restart: always
    networks:
      - viatab-network

  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - viatab-network

volumes:
  postgres-data:

networks:
  viatab-network:
    driver: bridge