name: Deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Test and Build"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: Package
        path: artifacts
        
    - name: Display structure of downloaded files
      run: ls -R artifacts
        
    - name: Deploy to server
      run: |
        echo "Deploying application..."
        # Add your deployment steps here
        # This could involve copying files to a server, updating a Docker container, etc.
        echo "Deployment completed"