name: Deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Test and Build"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download artifact
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        artifacts_url=$(curl -H "Authorization: Bearer $GITHUB_TOKEN" \
          https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}/artifacts \
          | jq -r '.artifacts[0].archive_download_url')
        
        curl -L -H "Authorization: Bearer $GITHUB_TOKEN" -o artifact.zip "$artifacts_url"
        unzip artifact.zip -d artifacts
      
    - name: Display structure of downloaded files
      run: ls -R artifacts
        
    - name: Deploy to server
      run: |
        echo "Deploying application..."
        # Add your deployment steps here
        # This could involve copying files to a server, updating a Docker container, etc.
        echo "Deployment completed"