name: Deploy to Minikube

on:
  workflow_run:
    workflows: ["Test, Build, and Push"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy-to-minikube:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Deploy to Minikube
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Start minikube
        uses: medyagh/setup-minikube@master
      
      - name: Lowercase the repo name
        run: echo "REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      
      - name: Deploy to minikube
        run: |
          echo "Applying deployment and service"
          minikube kubectl -- apply -f deployment.yaml
          minikube kubectl -- apply -f service.yaml
      
      - name: Update deployment image
        run: |
          echo "Updating deployment image"
          minikube kubectl -- set image deployment/viatab-deployment viatab=ghcr.io/${{ env.REPO_NAME }}:${{ github.sha }}
      
      - name: Verify deployment
        run: |
          echo "Verifying deployment"
          minikube kubectl -- get deployments
          minikube kubectl -- get pods
          minikube kubectl -- get services