name: Test, Build, and Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Build with Maven
      run: mvn clean package
      
    - name: Run tests
      run: mvn test
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Package
        path: target/*.jar
        retention-days: 5

  docker-build-and-push:
    needs: build
    name: Build and Push Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: Package
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Lowercase the repo name
        run: echo "REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.REPO_NAME }}:${{ github.sha }}

  deploy-to-minikube:
    needs: docker-build-and-push
    name: Deploy to Minikube
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Start minikube
        uses: medyagh/setup-minikube@master
      - name: Lowercase the repo name
        run: echo "REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      - name: Deploy to minikube
        run: |
          echo "Applying deployment and service"
          minikube kubectl -- apply -f deployment.yaml
          minikube kubectl -- apply -f service.yaml
      - name: Update deployment image
        run: |
          echo "Updating deployment image"
          minikube kubectl -- set image deployment/viatab-deployment viatab=ghcr.io/${{ env.REPO_NAME }}:${{ github.sha }}