name: CI/CD
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build, Test, and Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build and Test with Maven
        run: mvn -B package --file pom.xml
      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: Package
          path: target/*.jar
          if-no-files-found: error

  docker-build-and-push:
    needs: build-and-test
    name: Build and Push Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v3.1.2
        with:
          name: Package
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/viatab:${{ github.sha }} .
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push image to DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/viatab:${{ github.sha }}

  deploy-to-minikube:
    needs: docker-build-and-push
    name: Deploy to Minikube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start minikube
        uses: medyagh/setup-minikube@master
      - name: Deploy to minikube
        run: |
          minikube kubectl -- apply -f deployment.yaml
          minikube kubectl -- apply -f service.yaml
      - name: Update deployment image
        run: |
          minikube kubectl -- set image deployment/viatab-deployment viatab=${{ secrets.DOCKERHUB_USERNAME }}/viatab:${{ github.sha }}