name: CI/CD
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build, Test, and Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build and Test with Maven
        run: |
          echo "Starting Maven build and test"
          mvn -B clean verify --file pom.xml
          echo "Maven build and test completed"
      - name: List target directory
        run: ls -l target/
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: target/*.jar
          if-no-files-found: error

  docker-build-and-push:
    needs: build-and-test
    name: Build and Push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: Package
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/viatab:${{ github.sha }}

  deploy-to-minikube:
    needs: docker-build-and-push
    name: Deploy to Minikube
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Start minikube
        uses: medyagh/setup-minikube@master
      - name: Deploy to minikube
        run: |
          echo "Applying deployment and service"
          minikube kubectl -- apply -f deployment.yaml
          minikube kubectl -- apply -f service.yaml
      - name: Update deployment image
        run: |
          echo "Updating deployment image"
          minikube kubectl -- set image deployment/viatab-deployment viatab=${{ secrets.DOCKERHUB_USERNAME }}/viatab:${{ github.sha }}