name: Build and Test
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build and test with Maven
        run: mvn clean verify
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3.1.3
        with:
          name: Package
          path: target/*.jar
          if-no-files-found: warn
      - name: List target directory
        run: ls -l target/