name: Build and Deploy
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build with Maven
        run: mvn clean package
      - name: Deploy to server
        run: |
          echo "Add your deployment commands here"
          # For example:
          # scp target/your-app.jar user@your-server:/path/to/deploy
          # ssh user@your-server 'sudo systemctl restart your-app'
  code-quality:
    name: Code Quality Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run Checkstyle
        run: mvn checkstyle:check
      - name: Run SpotBugs
        run: mvn spotbugs:check
      - name: Run PMD
        run: mvn pmd:check
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: code-quality-reports
          path: target/site